### ISSUE TITLE
Keep sensitive data in binary

### ISSUE THREAD

**Issue by incker** [stouset/secrets#107]
Hello!

It is more a question. Is there a good way to keep sensitive data in binary?

Forward thank you!

**Comment by Bennett-Petzold** [comment]
That isn't within the scope of this library -- you may want to search or ask on different forums. https://www.reddit.com/r/rust/comments/seqmlz/storing_credentials_in_source_code/ has a discussion on this. But to answer nonetheless...

There is no safe way to package sensitive information in a binary. You can attempt arbitrarily complex ways of hiding the secret, but it will always be extractable.

Potential flawed approaches:
- Store it directly.
  - Trivially extractable using `strings`.
- Store it encrypted, and also store the decryption metadata in the binary.
  - The decryption keys, etc. needed to get the encrypted data are also trivially extractable using `strings`. An attacker can then use that to decrypt the data.
- Obfuscate the variable's location (e.g. putting the data in code sections instead of data sections).
  - The area of memory storing the variable can be found via reverse engineering sections of the code that use that secret.
- Store only the encrypted data, and give the user a key they provide the program to decrypt that data.
  - This can be effective if you're only concerned about unauthorized access to the secret, but all intended users of that program must have that key. So all intended users of the program have the ability to extract the secret.
